#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

scope="RELEASE_SCOPE.md"

require_text() {
  local text="$1"
  if ! grep -Fq -- "$text" "$scope"; then
    echo "missing release-scope text: $text" >&2
    exit 1
  fi
}

require_path() {
  local path="$1"
  if [[ ! -e "$path" ]]; then
    echo "missing release-scope baseline path: $path" >&2
    exit 1
  fi
}

if [[ ! -f "$scope" ]]; then
  echo "missing $scope" >&2
  exit 1
fi

require_text "# Release Scope Lock"
require_text "## Scope rule"
require_text "## Current release decision"
require_text "## Closed release items"
require_text "## Open release items"
require_text "## Review baseline"
require_text "## Non-claims"
require_text "## Fault-tolerance target and evidence matrix"
require_text "Fault-tolerance target"
require_text "Normal operation maintained when"
require_text "Evidence proving normal operation"
require_text "Fault-count boundary"
require_text "Healthy quorum"
require_text "synthesized reconstruction without a verified checkpoint"
require_text "No target-environment remote claim"
require_text "in-place Pebble/WAL repair"
require_text "No-go."
require_text "Release scope lock"
require_text "Review baseline"
require_text "Requirement traceability"
require_text "Deterministic timing boundary"
require_text "Missing dependency closure"
require_text "Owner-independent recovery"
require_text "Go/race/coverage gates"
require_text "Deterministic simulation"
require_text "Static/text audit"
require_text "Algorithm correspondence"
require_text "Local Jepsen restart/transport/storage gates"
require_text "Pin toolchain reproducibly"
require_text "Configuration-change ordering"
require_text "Configuration-change ordering, pinning, and finite durable replay"
require_text "one finite executed add/remove durable replay slice"
require_text "Ready durable-application failure handling"
require_text "Full EPaxos Revisited TOQ"
require_text "Paper fast-quorum parity"
require_text "Implemented fast quorum table"
require_text "Deterministic ProcessAt timing heuristic"
require_text "Chaos and fault-injection campaign"
require_text "Logical clock skew injection"
require_text "Clock pause handling"
require_text "Leap-second-style civil-time boundary"
require_text "VM rollback restart catch-up"
require_text "Storage/wire restart rollback simulation"
require_text "Local destructive-storage recovery"
require_text "Remote destructive-safety preflight"
require_text "preflight-only validation"
require_text "simulation/local-loopback release scope"
require_text "external multi-host Jepsen histories are outside"
require_text "OS wall-clock mutation"
require_text "actual mixed-version binary execution"
require_text "Bit-level persisted-record corruption"
require_text "Checkpoint-backed bit-level disk-corruption recovery"
require_text "TestCheckpointRepairRecoversBitFlippedPersistedEPaxosRecord"
require_text "TestCheckpointRepairRejectsCorruptCheckpointAndLeavesLiveData"
require_text "TestVerifyCheckpointAndRepairFromCheckpointRejectMissingCheckpoint"
require_text "TestVerifyCheckpointRejectsSemanticDataCorruption"
require_text "TestVerifyCheckpointCrashWindowMarkerRules"
require_text "TestRecoverReplicaFromLiveCheckpointRestoresStoppedReplica"
require_text "TestRecoverReplicaFromLiveCheckpointRejectsUnsupportedSource"
require_text "TestRecoverReplicaFromLiveCheckpointRejectsTargetOwnedFloorMismatch"
require_text "Crash-idempotent application"
require_text "API separation"
require_text "Transport security"
require_text "Request deadline budgets"
require_text "Request size limits"
require_text "Scan bounds"
require_text "Point latest-read semantics"
require_text "Scan latest-read semantics"
require_text "Binary value fidelity"
require_text "Health readiness split"
require_text "Observability"
require_text "Formal models"
require_text "tla/EPaxosRecoveryFive.cfg"
require_text "tla/EPaxosConfigTransition.cfg"
require_text "tla/EPaxosConfigRemoveTransition.cfg"
require_text "tla/EPaxosConfigChainTransition.cfg"
require_text "tla/EPaxosConfigReplay.cfg"
require_text "tla/EPaxosConfigRecovery.cfg"
require_text "tla/EPaxosRollbackAllocation.cfg"
require_text "tla/EPaxosRollbackAllocation.tla"
require_text "learned-before-fresh"
require_text "timeout-outcome wording only"
require_text "learned-before-fresh applied order"
require_text "tla/EPaxosOptimizedRecovery.tla"
require_text "tla/EPaxosOptimizedRecoverySeven.cfg"
require_text "tla/EPaxosTryPreAcceptBranches.cfg"
require_text "tla/EPaxosTryPreAcceptBranchesSeven.cfg"
require_text "TryPreAccept response branch-slice"
require_text "tla/EPaxosTryPreAcceptMessagePath.cfg"
require_text "tla/EPaxosTryPreAcceptMessagePathSeven.cfg"
require_text "TryPreAccept message-path coverage"
require_text "tla/EPaxosTryConflictForce.cfg"
require_text "tla/EPaxosTryConflictForceSeven.cfg"
require_text "force/defer quorum"
require_text "Config replay note"
require_text "Config replay limit"
require_text "durable restart replay"
require_text "generated \`6/6\` states"
require_text "default sync group uses replayed current voters"
require_text "remaining durable-replay non-claim"
require_text "stored historical config states"
require_text "Config recovery note"
require_text "Config recovery limit"
require_text "old slow quorum"
require_text "generated \`44/30\` states"
require_text "finite staged recovery-under-removal"
require_text "Configuration recovery under removal"
require_text "TestOldConfigRecoveryUsesPinnedVotersAfterRemoval"
require_text "emit no application command for the recovered no-op"
require_text "Config recovery de-dup note"
require_text "Config recovery de-dup limit"
require_text "tla/EPaxosConfigRecoveryDedup.cfg"
require_text "generated \`11/11\` states"
require_text "lost+duplicate response de-duplication"
require_text "does not model retries"
require_text "timer rebroadcast"
require_text "duplicate voter 3 prepare/accept responses do not advance Ready"
require_text "Config add-recovery note"
require_text "Config add-recovery limit"
require_text "generated \`15/15\` states"
require_text "finite staged recovery-after-addition"
require_text "Configuration recovery under addition"
require_text "TestOldConfigRecoveryUsesPinnedVotersAfterAddition"
require_text "no application command is emitted for the recovered no-op"
require_text "tla/EPaxosEvidenceQuery.tla"
require_text "tla/EPaxosEvidenceQuerySeven.cfg"
require_text "Evidence staleness note"
require_text "Evidence staleness limit"
require_text "tla/EPaxosEvidenceStaleness.cfg"
require_text "generated \`6/6\` states"
require_text "TestEvidenceStaleDuplicateCommittedTupleFallsBackToSlowAccept"
require_text "older-ballot \`MsgEvidenceResp\` is dropped before sender-record insertion"
require_text "same-ballot duplicate responses keep the first stale/empty record"
require_text "does not model retries, arbitrary network delivery, message loss"
require_text "TryPreAccept retry-timer finite model"
require_text "TryPreAccept retry-timer note"
require_text "TryPreAccept retry-timer limit"
require_text "tla/EPaxosTryPreAcceptRetry.cfg"
require_text "TestTryPreAcceptTimerDropsStaleEvidenceChecksBeforeRetry"
require_text "direct TLC generated \`10/10\` states"
require_text "deterministic retry rescheduling"
require_text "normal/ignore-marker retry rebroadcasts have no durable/application effects"
require_text "Configuration recovery retry-timer finite model"
require_text "Config recovery retry note"
require_text "Config recovery retry limit"
require_text "tla/EPaxosConfigRecoveryRetry.cfg"
require_text "TestOldConfigRecoveryRetryUsesPinnedVotersAfterRemoval"
require_text "TestOldConfigRecoveryRetryUsesPinnedVotersAfterAddition"
require_text "direct TLC generated \`8/8\` states"
require_text "old-config prepare/accept timer rebroadcast"
require_text "excludes added current voters"
require_text 'unique TLC `-metadir`'
require_text "Broader formal model coverage"
require_text "Semantic scan checking"
require_text "Fuzz stress campaigns"
require_text "Deployment manifest"
require_text "Data lifecycle"
require_text "Local mixed-version binary drill"
require_text "Capacity envelope"
require_text "Incident readiness"
require_text "Production limits"
require_text "API contracts"
require_text "Evidence bundle and go/no-go workflow"
require_text "EPAXOS.MD"
require_text "MODEL_EQ_REPORT.MD"
require_text "EPAXOS_IMPLEMENTATION_PROOF.md"
require_text "TestDSTFailureBoundarySlowQuorumSizesOneThroughSeven"
require_text "TestDSTStorageFailureRetriesOutstandingReadyExactlyOnceWithHealthyQuorum"
require_text "TestDSTStorageFailureBoundarySlowQuorumSizesOneThroughSeven"
require_text "TestTOQThreeNodeFastCommitUsesOptimizedQuorumWithCoveringAttrs"
require_text "TestAcceptRespIgnoresStaleBallotForCurrentAcceptRound"
require_text "TestStorageWireRestartUpgradeRollbackSimulationConvergesWithoutDuplicateApply"
require_text "0,0,1,1,2,2,3"
require_text "GitHub Actions are pinned to full 40-character commit SHAs"
require_text "TOQOneWayDelay"
require_text "tests/ci.sh"
require_text "tests/chaos_fault_campaign.sh"
require_text "tests/fuzz_stress_campaign.sh"
require_text "tests/jepsen_remote_preflight_audit.sh"
require_text "tests/operations_readiness_audit.sh"
require_text "deploy/systemd/kvnode@.service"
require_text "docs/operations/kvnode-data-lifecycle-incident-runbook.md"
require_text "examples/kv/cmd/kvcheckpoint"
require_text "TestRestoreRejectsCorruptCheckpointWithoutReplacingLiveData"
require_text "docs/operations/kvnode-upgrade-rollback.md"
require_text "tests/kvnode_capacity_envelope.sh"
require_text "tests/kvnode_incident_tabletop_drill.sh"
require_text "tests/kvnode_local_capacity_drill.sh"
require_text "tests/kvnode_local_runner.go"
require_text "custom Go runner sample"
require_text "status=local-go-runner-only"
require_text "go run -tags kvnode_local_runner ./tests/kvnode_local_runner.go --help"
require_text "measured target-environment capacity results remain open"
require_text "also locally exercised \`/faults/storage\`, \`/faults/transport\`, \`/readyz\`, \`/metrics\`"
require_text "three-node local wrapper sample"
require_text "locally rehearses the storage-failure and network-partition"
require_text "Operator-reviewed target-environment tabletop or live drill evidence remains open"
require_text "tests/kvnode_systemd_manifest_audit.sh"
require_text "tests/kvnode_mixed_version_drill.sh"
require_text "Local mixed-version binary drill"
require_text "KVNODE_SYSTEMD_ANALYZE=yes"
require_text "tests/go_no_go_workflow.sh"
require_text "release/EPAXOS_READINESS_EVIDENCE.md"
require_text "request-deadline-ms"
require_text "peer-listen"
require_text "admin-listen"
require_text "tls-cert"
require_text "tls-ca"
require_text "max-client-body-bytes"
require_text "max-peer-body-bytes"
require_text "max-admin-body-bytes"
require_text ".github/workflows/ci.yml"

require_path "EPAXOS.MD"
require_path "MODEL_EQ_REPORT.MD"
require_path "EPAXOS_IMPLEMENTATION_PROOF.md"
require_path "tests/ci.sh"
require_path "tests/chaos_fault_campaign.sh"
require_path "tests/fuzz_stress_campaign.sh"
require_path "tests/jepsen_remote_preflight_audit.sh"
require_path "tests/operations_readiness_audit.sh"
require_path "deploy/systemd/kvnode@.service"
require_path "deploy/systemd/kvnode.env.example"
require_path "docs/operations/kvnode-data-lifecycle-incident-runbook.md"
require_path "examples/kv/cmd/kvcheckpoint/main.go"
require_path "examples/kv/cmd/kvcheckpoint/main_test.go"
require_path "docs/operations/kvnode-upgrade-rollback.md"
require_path "tests/kvnode_capacity_envelope.sh"
require_path "tests/kvnode_incident_tabletop_drill.sh"
require_path "tests/kvnode_local_capacity_drill.sh"
require_path "tests/kvnode_local_runner.go"
require_path "tests/kvnode_systemd_manifest_audit.sh"
require_path "tests/kvnode_mixed_version_drill.sh"
require_path "tests/go_no_go_workflow.sh"
require_path "release/EPAXOS_READINESS_EVIDENCE.md"
require_path "tla/EPaxosRecoveryFive.cfg"
require_path "tla/EPaxosConfigTransition.cfg"
require_path "tla/EPaxosConfigRemoveTransition.cfg"
require_path "tla/EPaxosConfigChainTransition.cfg"
require_path "tla/EPaxosConfigReplay.tla"
require_path "tla/EPaxosConfigReplay.cfg"
require_path "tla/EPaxosConfigRecovery.tla"
require_path "tla/EPaxosConfigRecovery.cfg"
require_path "tla/EPaxosConfigRecoveryDedup.tla"
require_path "tla/EPaxosConfigRecoveryDedup.cfg"
require_path "tla/EPaxosConfigAddRecovery.tla"
require_path "tla/EPaxosConfigAddRecovery.cfg"
require_path "tla/EPaxosOptimizedRecovery.tla"
require_path "tla/EPaxosOptimizedRecoverySeven.cfg"
require_path "tla/EPaxosTryPreAcceptBranches.tla"
require_path "tla/EPaxosTryPreAcceptBranches.cfg"
require_path "tla/EPaxosTryPreAcceptBranchesFive.cfg"
require_path "tla/EPaxosTryPreAcceptBranchesSeven.cfg"
require_path "tla/EPaxosTryPreAcceptMessagePath.tla"
require_path "tla/EPaxosTryPreAcceptMessagePath.cfg"
require_path "tla/EPaxosTryPreAcceptMessagePathFive.cfg"
require_path "tla/EPaxosTryPreAcceptMessagePathSeven.cfg"
require_path "tla/EPaxosTryConflictForce.tla"
require_path "tla/EPaxosTryConflictForce.cfg"
require_path "tla/EPaxosTryConflictForceFive.cfg"
require_path "tla/EPaxosTryConflictForceSeven.cfg"
require_path "tla/EPaxosEvidenceQuery.tla"
require_path "tla/EPaxosEvidenceQuerySeven.cfg"
require_path "tla/EPaxosEvidenceStaleness.tla"
require_path "tla/EPaxosEvidenceStaleness.cfg"
require_path "tla/EPaxosTryPreAcceptRetry.tla"
require_path "tla/EPaxosTryPreAcceptRetry.cfg"
require_path "tla/EPaxosConfigRecoveryRetry.tla"
require_path "tla/EPaxosConfigRecoveryRetry.cfg"
require_path "tla/EPaxosConfigTransition.tla"
require_path "tla/EPaxosConfigRemoveTransition.tla"
require_path "tla/EPaxosConfigChainTransition.tla"
require_path "tla/EPaxosRollbackAllocation.tla"
require_path "tla/EPaxosRollbackAllocation.cfg"
require_path ".github/workflows/ci.yml"

if grep -Fq -- "REQUIREMENTS_TRACE.md" "$scope"; then
  echo "release-scope lock must stay self-contained" >&2
  exit 1
fi
